export const phishingEmails = [
  {
    id: 1,
    sender: "security@amaz0n-verify.com",
    senderDisplay: "Amazon Security Team",
    subject: "⚠️ Your account has been compromised - Immediate action required",
    body: "Dear Valued Customer,\n\nWe have detected unusual activity on your Amazon account. Someone from an unrecognized device attempted to access your account.\n\nTo protect your account, please verify your identity immediately by clicking the link below:\n\nhttps://amaz0n-verify.com/secure-login\n\nIf you don't verify within 24 hours, your account will be permanently suspended.\n\nAmazon Security Team",
    isPhishing: true,
    difficulty: "easy",
    redFlags: [
      "Sender domain is 'amaz0n-verify.com' (note the zero instead of 'o')",
      "Creates urgency with threats of account suspension",
      "Generic greeting 'Dear Valued Customer' instead of your name",
      "Suspicious link URL doesn't match official Amazon domain"
    ],
  },
  {
    id: 2,
    sender: "noreply@github.com",
    senderDisplay: "GitHub",
    subject: "You have a new follower on GitHub",
    body: "Hey there!\n\n@john_developer just followed you on GitHub.\n\nCheck out their profile: https://github.com/john_developer\n\nYou're receiving this email because you opted in to email notifications.\n\nManage your notification settings:\nhttps://github.com/settings/notifications\n\n— GitHub",
    isPhishing: false,
    difficulty: "easy",
    redFlags: [],
  },
  {
    id: 3,
    sender: "helpdesk@m1crosoft-support.net",
    senderDisplay: "Microsoft Support",
    subject: "Your Microsoft 365 subscription payment failed",
    body: "Dear User,\n\nWe were unable to process your payment for Microsoft 365 subscription. Your subscription will expire in 48 hours unless you update your payment information.\n\nClick here to update your payment method:\nhttps://m1crosoft-support.net/billing/update\n\nPlease provide your credit card details and billing address to continue using our services.\n\nMicrosoft Support Team\nRef: MS-2024-8847291",
    isPhishing: true,
    difficulty: "medium",
    redFlags: [
      "Domain 'm1crosoft-support.net' uses '1' instead of 'i'",
      "Asks you to provide credit card details via link",
      "Creates time pressure with 48-hour deadline",
      "Generic 'Dear User' greeting"
    ],
  },
  {
    id: 4,
    sender: "notifications@linkedin.com",
    senderDisplay: "LinkedIn",
    subject: "You appeared in 15 searches this week",
    body: "Hi Siddhant,\n\nYou appeared in 15 searches this week.\n\nSee who's looking at your profile:\nhttps://www.linkedin.com/me/search-appearances/\n\nProfile views: 42 (up 12% from last week)\n\nTips to increase your visibility:\n- Update your headline\n- Add recent achievements\n- Engage with posts in your network\n\nLinkedIn Notifications\nUnsubscribe: https://www.linkedin.com/comm/unsubscribe",
    isPhishing: false,
    difficulty: "medium",
    redFlags: [],
  },
  {
    id: 5,
    sender: "ceo@company-internal.com",
    senderDisplay: "Rajesh Kumar (CEO)",
    subject: "URGENT: Wire Transfer Needed Today",
    body: "Hi,\n\nI need you to process an urgent wire transfer of ₹5,00,000 to a vendor today. This is time-sensitive and confidential.\n\nPlease don't discuss this with anyone else. I'm in a meeting and can't call right now.\n\nBank details:\nAccount: 9876543210\nIFSC: SBIN0001234\nName: Global Tech Solutions\n\nConfirm once done.\n\nRegards,\nRajesh Kumar\nCEO, Your Company",
    isPhishing: true,
    difficulty: "hard",
    redFlags: [
      "CEO urgently requesting money transfer via email (Business Email Compromise)",
      "Insists on secrecy ('don't discuss with anyone')",
      "Can't verify via phone call ('in a meeting')",
      "External domain 'company-internal.com' pretending to be internal",
      "Unusual request bypassing normal financial procedures"
    ],
  },
  {
    id: 6,
    sender: "no-reply@google.com",
    senderDisplay: "Google",
    subject: "Security alert: New sign-in from Chrome on Windows",
    body: "New sign-in to your Google Account\n\nYour Google Account was just signed in to from Chrome on a Windows device.\n\nDevice: Windows PC\nLocation: Mumbai, India\nTime: August 19, 2026 10:30 AM IST\n\nIf this was you, no further action is needed.\nIf this wasn't you, review your account activity:\nhttps://myaccount.google.com/security\n\n— Google Accounts team",
    isPhishing: false,
    difficulty: "hard",
    redFlags: [],
  },
  {
    id: 7,
    sender: "prize@lucky-winner-2024.com",
    senderDisplay: "International Lottery Commission",
    subject: "🎉 Congratulations! You've Won $1,000,000!",
    body: "CONGRATULATIONS!!!\n\nYour email address was randomly selected in our International Digital Lottery Draw.\n\nYou have won: $1,000,000 USD\nRef No: ILC/2024/WIN/8847\n\nTo claim your prize, send us:\n- Full Name\n- Phone Number\n- Bank Account Details\n- Copy of your ID\n\nProcessing fee: Only $99.99\n\nContact our claims agent:\nDr. James Wilson\njames.wilson@lucky-winner-2024.com\n\nAct within 7 days or your prize will be forfeited!",
    isPhishing: true,
    difficulty: "easy",
    redFlags: [
      "Too good to be true — random lottery win",
      "Asks for personal/banking information",
      "Requires payment to receive a 'prize'",
      "Excessive use of caps and exclamation marks",
      "Time pressure to respond"
    ],
  },
  {
    id: 8,
    sender: "it-admin@yourcompany-reset.com",
    senderDisplay: "IT Department",
    subject: "Password Reset Required - New Security Policy",
    body: "Dear Employee,\n\nAs part of our new security policy, all employees must reset their passwords within the next 24 hours.\n\nPlease use the secure portal below to reset your password:\nhttps://yourcompany-reset.com/password-change\n\nYou will need to enter:\n- Current password\n- Employee ID\n- Date of birth\n\nFailure to comply will result in account lockout.\n\nIT Security Team",
    isPhishing: true,
    difficulty: "medium",
    redFlags: [
      "External domain 'yourcompany-reset.com' pretending to be internal IT",
      "Asks for current password (IT never needs your current password)",
      "Requests unnecessary personal info (date of birth)",
      "Threatens account lockout to create urgency",
      "Generic 'Dear Employee' greeting"
    ],
  },
  {
    id: 9,
    sender: "shipping@flipkart.com",
    senderDisplay: "Flipkart",
    subject: "Your order #FK-28394756 has been shipped!",
    body: "Hi Siddhant,\n\nGreat news! Your order has been shipped.\n\nOrder #FK-28394756\nItem: boAt Airdopes 141 Bluetooth Earbuds\nEstimated Delivery: August 22, 2026\n\nTrack your package:\nhttps://www.flipkart.com/track/FK-28394756\n\nDelivery Address:\nMumbai, Maharashtra 400001\n\nNeed help? Contact us:\nhttps://www.flipkart.com/helpcentre\n\nHappy Shopping!\nFlipkart",
    isPhishing: false,
    difficulty: "hard",
    redFlags: [],
  },
  {
    id: 10,
    sender: "admin@paypa1-secure.com",
    senderDisplay: "PayPal Security",
    subject: "Unusual activity detected on your PayPal account",
    body: "Dear PayPal Customer,\n\nWe've detected unusual login activity on your PayPal account from the following location:\n\nIP: 185.243.112.89\nCountry: Russia\nTime: 2026-08-18 23:45 UTC\n\nIf this wasn't you, secure your account immediately:\nhttps://paypa1-secure.com/verify\n\nYou must verify your identity within 12 hours or we'll have to restrict your account.\n\nPayPal Security Center\nThis is an automated message. Do not reply.",
    isPhishing: true,
    difficulty: "medium",
    redFlags: [
      "Domain 'paypa1-secure.com' uses '1' instead of 'l'",
      "Creates urgency with 12-hour deadline",
      "Generic greeting instead of your name",
      "Suspicious verification link"
    ],
  },
];
